name: Deployment Pipeline

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "✅ Workflow triggered"
