name: Deployment Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:

  build-and-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "✅ Workflow triggered through agent"
          sleep 31s
          exit 1
          echo "✅ Workflow completed through agent"
